### ISSUE TITLE
[filterQueryBuilder] TS Compilation error

### ISSUE THREAD

**Issue by tonytoth** [TriPSs/nestjs-query#20]
Hi,
I am not sure if I have to set something in ```tsconfig``` but when Nest.js is trying to compile there is a typescript error I guess:
```
/usr/src/app/node_modules/@ptc-org/nestjs-query-typeorm/src/services/typeorm-query.service.js:27
        this.filterQueryBuilder = opts?.filterQueryBuilder ?? new query_1.FilterQueryBuilder(this.repo);
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/packages/query-typeorm/src/services/index.ts:1:1)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by TriPSs** [comment]
Can you share your `tsconfig`?

**Comment by tonytoth** [comment]
Sure.
```
{
  "compilerOptions": {
    "module": "commonjs",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2019",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "paths": {},
    "noImplicitAny": false,
    "skipLibCheck": true,
    "declaration": false,
  },
  "exclude": [
    "node_modules",
    "dist",
  ]
}

```

**Comment by TriPSs** [comment]
Hmm not quite sure, don't see anything weird, you could try to configure it exactly as [tsconfig file of examples](https://github.com/TriPSs/nestjs-query/blob/master/examples/tsconfig.app.json)

**Comment by tonytoth** [comment]
Aight, I'll come back with a response soon.

**Comment by tonytoth** [comment]
I think it was something related with the node version I had, it was fixed after upgrading to ```node:16-alpine3.15```
