### ISSUE TITLE
Shouldn't the generated `input CreateXxx` type have non-null field types when applicable?

### ISSUE THREAD

**Issue by ValentinVignal** [TriPSs/nestjs-query#78]
I'm not sure whether this is a _"bug"_ or if there are some edge cases I don't know about. 

**Describe the bug**

I followed the the introduction getting started/install/example at https://tripss.github.io/nestjs-query/docs/introduction/example

From the `TodoItemEntity` :

```ts
@Entity()
export class TodoItemEntity {
  @PrimaryGeneratedColumn()
  id!: string;

  @Column()
  title!: string;

  @Column()
  completed!: boolean;

  @CreateDateColumn()
  created!: Date;

  @UpdateDateColumn()
  updated!: Date;
}
```

and `TodoItemDTO`:

```ts
@ObjectType('TodoItem')
export class TodoItemDTO {
  @IDField(() => ID)
  id!: number;

  @FilterableField()
  title!: string;

  @FilterableField()
  completed!: boolean;

  @Field(() => GraphQLISODateTime)
  created!: Date;

  @Field(() => GraphQLISODateTime)
  updated!: Date;
}
```

It generates the schema 

```graphql
type TodoItem {
  id: ID!
  title: String!
  completed: Boolean!
  created: DateTime!
  updated: DateTime!
}
```

which seems correct.

If I look at the input types for the updates: 

```graphql
input UpdateTodoItem {
  id: ID
  title: String
  completed: Boolean
  created: DateTime
  updated: DateTime
}
```

It makes sense for the update to only have nullable types. If `title` is `null`, it means it is not being updated.

However, for the creation input type:

```graphql
input CreateTodoItem {
  id: ID
  title: String
  completed: Boolean
  created: DateTime
  updated: DateTime
}
```

Shouldn't `title` and `completed` be non-nullable as `title` and `completed` are not nullable?

For example, if I run

```graphql
mutation {
  createOneTodoItem(
    input: { todoItem: { title: "Create One Todo Item"} }
  ) {
    id
    title
    completed
    created
    updated
  }
}
```

In the graphql playground, I get the error:

```json
{
  "errors": [
    {
      "message": "null value in column \"completed\" violates not-null constraint",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createOneTodoItem"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "INSERT INTO \"todo_item_entity\"(\"title\", \"completed\", \"created\", \"updated\") VALUES ($1, DEFAULT, DEFAULT, DEFAULT) RETURNING \"id\", \"created\", \"updated\"",
          "parameters": [
            "Create One Todo Item"
          ],
          "driverError": {
            "length": 272,
            "name": "error",
            "severity": "ERROR",
            "code": "23502",
            "detail": "Failing row contains (3, Create One Todo Item, null, 2023-01-13 06:31:35.856241, 2023-01-13 06:31:35.856241).",
            "schema": "public",
            "table": "todo_item_entity",
            "column": "completed",
            "file": "execMain.c",
            "line": "2042",
            "routine": "ExecConstraints"
          },
          "length": 272,
          "severity": "ERROR",
          "code": "23502",
          "detail": "Failing row contains (3, Create One Todo Item, null, 2023-01-13 06:31:35.856241, 2023-01-13 06:31:35.856241).",
          "schema": "public",
          "table": "todo_item_entity",
          "column": "completed",
          "file": "execMain.c",
          "line": "2042",
          "routine": "ExecConstraints",
          "stacktrace": [
            "QueryFailedError: null value in column \"completed\" violates not-null constraint",
            "    at PostgresQueryRunner.query (/Users/valentin/Perso/Projects/reproducible/src/driver/postgres/PostgresQueryRunner.ts:299:19)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at InsertQueryBuilder.execute (/Users/valentin/Perso/Projects/reproducible/src/query-builder/InsertQueryBuilder.ts:163:33)",
            "    at SubjectExecutor.executeInsertOperations (/Users/valentin/Perso/Projects/reproducible/src/persistence/SubjectExecutor.ts:428:42)",
            "    at SubjectExecutor.execute (/Users/valentin/Perso/Projects/reproducible/src/persistence/SubjectExecutor.ts:137:9)",
            "    at EntityPersistExecutor.execute (/Users/valentin/Perso/Projects/reproducible/src/persistence/EntityPersistExecutor.ts:197:21)",
            "    at DefaultAssembler.convertAsyncToDTO (/Users/valentin/Perso/Projects/reproducible/packages/core/src/assemblers/abstract.assembler.ts:64:15)",
            "    at AutoResolver.createOne (/Users/valentin/Perso/Projects/reproducible/packages/query-graphql/src/resolvers/create.resolver.ts:141:25)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

which is a sql error. It would be better to catch is on the graphql level even before trying to run the sql query.

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
1. Follow the introduction part in https://tripss.github.io/nestjs-query/docs/introduction/example (you can also checkout https://github.com/ValentinVignal/reproducible/tree/ptc-org/nestjs-query/update-and-create-types)
2. Run `npm start`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Node Version: v16.14.2
 - Nestjs-query Versions:
   - @ptc-org/nestjs-query-core@1.1.4
   - @ptc-org/nestjs-query-graphql@1.1.4
   -  @ptc-org/nestjs-query-typeorm@1.1.4

**Comment by TriPSs** [comment]
Since you defined the `completed` to not have a default value you should provide it when creating.

**Comment by ValentinVignal** [comment]
> Since you defined the completed to not have a default value you should provide it when creating.

Yes, I agree, it should be provided, I want to force the client to provide it, and I don't want to set a default value.
What I'm trying to say is that in the schema, it should be:

```graphql
input CreateTodoItem {
  // .. 
  title: String!
  completed: Boolean! # <- Non nullable
  // .. 
}
```

I can achieve this result with a custom `CreateDTOClass`. But I was wondering whether the automatically generated `CreateDTOClass` should be 

```graphql
input CreateTodoItem {
  // .. 
  title: String!
  completed: Boolean! # <- Non nullable
  // .. 
}
```

too?

**Comment by TriPSs** [comment]
I think you are right, the default generated `CreateTodoItem` should indeed mark all fields as required.
